// generated by stringer -type=EventType; DO NOT EDIT

package comm

import "fmt"

const _EventTypeName = "RequestedEventBuildEventBuildEventSquashStartSaveBuildEventSquashFinishSaveBuildEventSquashStartSquashBuildEventSquashFinishSquashBuildEventSquashStartLoadBuildEventSquashFinishLoadBuildCompletedEventTagEventTagCompletedEventPushEventPushCompletedEventCompletedEvent"

var _EventTypeIndex = [...]uint16{14, 24, 49, 75, 102, 130, 155, 181, 200, 208, 225, 234, 252, 266}

func (i EventType) String() string {
	if i >= EventType(len(_EventTypeIndex)) {
		return fmt.Sprintf("EventType(%d)", i)
	}
	hi := _EventTypeIndex[i]
	lo := uint16(0)
	if i > 0 {
		lo = _EventTypeIndex[i-1]
	}
	return _EventTypeName[lo:hi]
}
