// generated by stringer -type=EventType; DO NOT EDIT

package comm

import "fmt"

const _EventType_name = "RequestedEventBuildEventBuildEventSquashStartSaveBuildEventSquashFinishSaveBuildEventSquashStartSquashBuildEventSquashFinishSquashBuildEventSquashStartLoadBuildEventSquashFinishLoadBuildCompletedEventTagEventTagCompletedEventPushEventPushCompletedEventCompletedEvent"

var _EventType_index = [...]uint16{14, 24, 49, 75, 102, 130, 155, 181, 200, 208, 225, 234, 252, 266}

func (i EventType) String() string {
	if i >= EventType(len(_EventType_index)) {
		return fmt.Sprintf("EventType(%d)", i)
	}
	hi := _EventType_index[i]
	lo := uint16(0)
	if i > 0 {
		lo = _EventType_index[i-1]
	}
	return _EventType_name[lo:hi]
}
