// generated by stringer -type=EventType; DO NOT EDIT

package comm

import "fmt"

const _EventTypeName = "RequestedEventBuildEventBuildEventSquashStartExportBuildEventSquashFinishExportBuildEventSquashStartSquashBuildEventSquashFinishSquashBuildEventSquashStartImportBuildEventSquashFinishImportBuildCompletedEventTagEventTagCompletedEventPushEventPushCompletedEventCompletedEvent"

var _EventTypeIndex = [...]uint16{14, 24, 51, 79, 106, 134, 161, 189, 208, 216, 233, 242, 260, 274}

func (i EventType) String() string {
	if i >= EventType(len(_EventTypeIndex)) {
		return fmt.Sprintf("EventType(%d)", i)
	}
	hi := _EventTypeIndex[i]
	lo := uint16(0)
	if i > 0 {
		lo = _EventTypeIndex[i-1]
	}
	return _EventTypeName[lo:hi]
}
